### ISSUE TITLE
Persist Gateway interval configuration after restart

### ISSUE THREAD

**Issue by jfreves** [SAIC-iSmart-API/saic-python-mqtt-gateway#142]
I usually change the Gateway inactive refresh period to a different value than the default but whenever the addon is restarted the value changes back to the default value.
Can this Gateway configuration be persisted instead?

**Comment by nanomad** [comment]
Technically it should already be handled vie the configure_by_message() function. If it is not working maybe it has to do with the MQTT client state not being cleared. Are you publishing those messges with the retain flag set?

**Comment by jfreves** [comment]
I have an input in my dashboard and use it to update the value, I'm not publishing messages directly.
<img width="457" alt="image" src="https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/75815666/da1cbf40-7030-41e9-9d41-e622e04fa001">

**Comment by pmannk** [comment]
> Technically it should already be handled vie the configure_by_message() function. If it is not working maybe it has to do with the MQTT client state not being cleared. Are you publishing those messges with the retain flag set?

I've tried (unsuccessfully) to retain the refresh period.
YAML config of the entity:
```
    - name: mg4_refresh_active
      state_topic: "saic/xxx@gmail.com/vehicles/xxx/refresh/period/active"
      command_topic: "saic/xxx@gmail.com/vehicles/xxx/refresh/period/active/set"
      retain: true
      options:
        - "30"
        - "900"
        - "3600"
```
If I pick "900" as the value in HA I can see it's retained when I shut down the SAIC MQTT Gateway (Python) add-on.
As soon as I start the add-on I see the MQTT value revert to 30, and in the SAIC logs I see:
`2024-01-30 22:22:13,590 [  INFO  ] Setting active query interval in vehicle handler for VIN xxx to 0:00:30 - vehicle`
