### ISSUE TITLE
Setting SAIC_URI in docker-compose.yml

### ISSUE THREAD

**Issue by paulhomes** [SAIC-iSmart-API/saic-python-mqtt-gateway#18]
Hi,

I am based in Australia where the iSmart app uses tap-au.soimt.com (as seen in local DNS logs). Whilst the readme doesn't mention an environment variable for setting SAIC_URL I saw that it looks like it is loaded in mqtt_gateway.py and tried it out with the following in my docker-compose.yml:

```
services:
  saic-mqtt-gateway:
    image: "saicismartapi/saic-python-mqtt-gateway:latest"
    container_name: "saic-mqtt-gateway"
    environment:
      ...
      - SAIC_URI=https://tap-au.soimt.com
      ...
```
When I started the container it exited with an account not registered error. I saw from the DNS logs that it was trying to use the default tap-eu.soimt.com server.  I ended up cloning the repository, changing the default SAIC_URL in mqtt_gateway.py and building a local docker image and then it worked ok and I was able to see the results in MQTT.

Do you see any reason why the docker-compose.yml environment variable method would not override the default from the code? I've had a look through the code and can't see why SAIC_USER can be set that way but SAIC_URL cannot - I'm still a bit of a Python newbie though.

Thanks
Paul
