### ISSUE TITLE
Feature Request: Home Assistant auto-discovery

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#38]
This has been requested in the Italian MG community. 
It would be nice if the gateway could publish the /config topic for HA auto-discovery. 

@tosate I'm currently working on it. Just thought about opening a formal feature request to allow for potential discussion. My plan is to have this feature enabled by default with an option to disable it via config:
- HA_DISCOVERY_ENABLED=True
- HA_DISCOVERY_PREFIX=homeassistant

**Comment by tosate** [comment]
Hi @nanomad 

I am also using the gateway with home assistant. This sounds great!
It would minimize the configuration effort in HA. You need to publish the configuration under a specific topics
like `<HA_DISCOVERY_PREFIX>/<component>/[<node_id>/]<object_id>/config`

Would this be something like
- `homeassistant/binary_sensor/<vehicle_id>/engine_running/config`
- `homeassistant/binary_sensor/<vehicle_id>/charging/config`
- `homeassistant/binary_sensor/<vehicle_id>/soc/config`

**Comment by nanomad** [comment]
Yep. I've got a PoC locally but there are a TON of sensors to configure.

I'll open a new feature request and relative pr to publish the GPS position as a JSON object as it allows for the device tracker integration to work flawlessly with little configuration

**Comment by tosate** [comment]
My HA configuration looks like this:
```
mqtt:
  sensor:
    - name: ev_longitude
      state_topic: saic/<user>/vehicles/<vehicle id>/location/longitude
      payload_not_available: "0.000000"
    - name: ev_latitude
      state_topic: saic/<user>/vehicles/<vehicle id>/location/latitude
      payload_not_available: "0.000000"

template:
  - binary_sensor:
    - name: mg_zs_ev_pos
      state: "{{ states('sensor.ev_running') }}"
      attributes:
        source_type: gps
        latitude: "{{ states('sensor.ev_latitude') }}"
        longitude: "{{ states('sensor.ev_longitude') }}"
```

I use this to display the location of the car on a [Map Card](https://www.home-assistant.io/dashboards/map/)
Using the [Device Tracker](https://www.home-assistant.io/integrations/device_tracker/) seems to be the more powerful solution.

But how do you configure the Device Tracker with the JSON string?

**Comment by nanomad** [comment]
That's correct. My current HA config is the following:
```
mqtt:
  device_tracker:
    - name: MG gps position
      unique_id: <VIN>_gps_position
      json_attributes_topic: "saic/<EMAIL>/vehicles/<VIN>/location/position"
```

This gets rid of any HA-side computation
