### ISSUE TITLE
QUESTION: Trigger refresh inside HA via automation

### ISSUE THREAD

**Issue by maglat** [SAIC-iSmart-API/saic-python-mqtt-gateway#81]
This is just a question. I have SAIC 0.3. successfully running in Home Assistant. The automatical refresh interval is set to the standard 120 seconds. I would like to keep that way so the V12 batterie is not stressed that much. 

I would like to trigger a manual refresh the data via automation, when I enter my home zone. reason of that, I have an automation which automatically opens the garage door. In the meanwhile, this ones triggers as soon my MG enters the home zone. After the refresh interval is very long, the garage opens too late in my opinion. So I would like to do the refresh manually, as soon me as person (my iphones) enters the home zone, refresh of SAIC should trigger to get the new MG GPS position. So the garage automation get started more or less at the same time. 

Someone can be provide the small piece of code I need to enter at the bottom of my automation to trigger the refresh?

Thank you all very much.

**Comment by tosate** [comment]
Hi @maglat 

your automation should trigger an action that sends a MQTT message to force the refresh:

```
action:
    service: mqtt.publish
    data:
      topic: "saic/<saic_user>/vehicles/<vehicle_id>/refresh/mode/set"
      payload: "force"
```
